/* Copyright 2014 Samsung Electronics Co., Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#include "globals.h"

static const char* generated_source = ""
"var tmp, a, b = 1, c = 2, d, e = 3, g = 4;\n"
"\n"
"var count = 1000;\n"
"\n"
"tmp = b * c;\n"
"a = tmp + g;\n"
"d = tmp * e + a;\n"
"\n"
"var waitTime = 600000;\n"
"var numOfIterations = 10;\n"
"\n"
"while (1)\n"
"{\n"
"for (var j = 0; j < numOfIterations / 2; j += 1)\n"
"{\n"
"LEDOn(12);\n"
"LEDOn(13);\n"
"LEDOn(14);\n"
"LEDOn(15);\n"
"wait(waitTime * 2);\n"
"LEDOff(12);\n"
"LEDOff(13);\n"
"LEDOff(14);\n"
"LEDOff(15);\n"
"wait(waitTime * 2);\n"
"}\n"
"\n"
"for (var j = 0; j < numOfIterations; j += 1)\n"
"{\n"
"LEDOn(12);\n"
"wait(waitTime);\n"
"LEDOff(12);\n"
"wait(waitTime);\n"
"LEDOn(13);\n"
"wait(waitTime);\n"
"LEDOff(13);\n"
"wait(waitTime);\n"
"LEDOn(14);\n"
"wait(waitTime);\n"
"LEDOff(14);\n"
"wait(waitTime);\n"
"LEDOn(15);\n"
"wait(waitTime);\n"
"LEDOff(15);\n"
"wait(waitTime);\n"
"}\n"
"\n"
"for (var j = 0; j < numOfIterations; j += 1)\n"
"{\n"
"LEDOn(12);\n"
"wait(waitTime);\n"
"LEDOff(12);\n"
"LEDOn(13);\n"
"wait(waitTime);\n"
"LEDOff(13);\n"
"LEDOn(14);\n"
"wait(waitTime);\n"
"LEDOff(14);\n"
"LEDOn(15);\n"
"wait(waitTime);\n"
"LEDOff(15);\n"
"}\n"
"\n"
"for (var j = 0; j < numOfIterations; j += 1)\n"
"{\n"
"LEDOn(12);\n"
"wait(waitTime / 2);\n"
"LEDOff(12);\n"
"LEDOn(13);\n"
"wait(waitTime / 2);\n"
"LEDOff(13);\n"
"LEDOn(14);\n"
"wait(waitTime / 2);\n"
"LEDOff(14);\n"
"LEDOn(15);\n"
"wait(waitTime / 2);\n"
"LEDOff(15);\n"
"}\n"
"\n"
"for (var j = 0; j < numOfIterations; j += 1)\n"
"{\n"
"LEDOn(12);\n"
"wait(waitTime / 3);\n"
"LEDOff(12);\n"
"LEDOn(13);\n"
"wait(waitTime / 3);\n"
"LEDOff(13);\n"
"LEDOn(14);\n"
"wait(waitTime / 3);\n"
"LEDOff(14);\n"
"LEDOn(15);\n"
"wait(waitTime / 3);\n"
"LEDOff(15);\n"
"}\n"
"\n"
"for (var j = 0; j < numOfIterations; j += 1)\n"
"{\n"
"LEDOn(12);\n"
"wait(waitTime / 6);\n"
"LEDOff(12);\n"
"LEDOn(13);\n"
"wait(waitTime / 6);\n"
"LEDOff(13);\n"
"LEDOn(14);\n"
"wait(waitTime / 6);\n"
"LEDOff(14);\n"
"LEDOn(15);\n"
"wait(waitTime / 6);\n"
"LEDOff(15);\n"
"}\n"
"}\n"
;
